apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: minio
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_SECRET_ACCESS_KEY: bWluaWkxMjM=
  rootUser: bWluaW8=
  rootPassword: bWluaWkxMjM=

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: metastore
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_SECRET_ACCESS_KEY: bWluaWkxMjM=

---
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: orchestrator
data:
  GIT_SYNC_USERNAME: bWluaW8=
  GITSYNC_USERNAME: bWluaW8=
  GIT_SYNC_PASSWORD: bWluaWkxMjM=
  GITSYNC_PASSWORD: bWluaWkxMjM=

# echo -n 'minio' | base64  # para AWS_ACCESS_KEY_ID
# echo -n 'minio123' | base64  # para AWS_SECRET_ACCESS_KEY
