apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nessie
  namespace: gitops
spec:
  project: default
  destination:
    name: 'victor-lab'
    namespace: nessie
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - repoURL: 'https://github.com/victoru2/trino-lakehouse-lab.git'
    targetRevision: main
    ref: trino-lakehouse-lab
  - repoURL: https://charts.bitnami.com/bitnami
    chart: nessie
    targetRevision: 1.0.0
    helm:
      valueFiles:
      - $trino-lakehouse-lab/metastore/helm/values.yaml
