minio:
  target: prod
  outputs:
    prod:
      type: trino
      threads: 1
      catalog: minio
      schema: landing
      host: 34.171.1.7
      port: 8080
      user: trino

iceberg_bronze:
  target: prod
  outputs:
    prod:
      type: trino
      threads: 1
      catalog: iceberg
      schema: bronze
      host: 34.171.1.7
      port: 8080
      user: trino

iceberg_silver:
  target: prod
  outputs:
    prod:
      type: trino
      threads: 1
      catalog: iceberg
      schema: silver
      host: 34.171.1.7
      port: 8080
      user: trino

iceberg_gold:
  target: prod
  outputs:
    prod:
      type: trino
      threads: 1
      catalog: iceberg
      schema: gold
      host: 34.171.1.7
      port: 8080
      user: trino
