common: &common_settings
  type: trino
  threads: 1
  host: trino.warehouse.svc.cluster.local
  port: 8080
  user: trino

minio:
  target: prod
  outputs:
    prod:
      !!merge <<: *common_settings
      catalog: minio
      schema: landing
    dev:
      !!merge <<: *common_settings
      catalog: minio
      schema: landing

iceberg_bronze:
  target: prod
  outputs:
    prod:
      !!merge <<: *common_settings
      catalog: iceberg
      schema: bronze
    dev:
      !!merge <<: *common_settings
      catalog: iceberg
      schema: bronze

iceberg_silver:
  target: prod
  outputs:
    prod:
      !!merge <<: *common_settings
      catalog: iceberg
      schema: silver
    dev:
      !!merge <<: *common_settings
      catalog: iceberg
      schema: silver

iceberg_gold:
  target: prod
  outputs:
    prod:
      !!merge <<: *common_settings
      catalog: iceberg
      schema: gold
    dev:
      !!merge <<: *common_settings
      catalog: iceberg
      schema: gold
