minio:
  target: prod
  outputs:
    prod:
      type: trino
      threads: 1
      catalog: minio
      schema: landing
      host: localhost
      port: 8080
      user: trino

iceberg:
  target: prod
  outputs:
    prod:
      type: trino
      threads: 1
      catalog: iceberg
      schema: stage
      host: localhost
      port: 8080
      user: trino
