apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: orchestrator
data:
  GIT_SYNC_USERNAME: myusername
  GITSYNC_USERNAME: myusername
  GIT_SYNC_PASSWORD: mypassword
  GITSYNC_PASSWORD: mypassword
