apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: gitops
spec:
  project: default
  destination:
    name: 'victor-lab'
    namespace: orchestrator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - repoURL: 'https://github.com/victoru2/trino-lakehouse-lab.git'
    targetRevision: main
    ref: trino-lakehouse-lab
  - repoURL: https://airflow.apache.org
    chart: airflow
    targetRevision: 1.15.0
    helm:
      valueFiles:
      - $trino-lakehouse-lab/airflow/helm/values.yaml
