apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: gitops
spec:
  project: default
  destination:
    name: 'victor-lab'
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - repoURL: 'https://github.com/victoru2/trino-lakehouse-lab.git'
    targetRevision: main
    ref: trino-lakehouse-lab
  - repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.2.0
    helm:
      valueFiles:
      - $trino-lakehouse-lab/minio/helm/values.yaml
