image:
  repository: trinodb/trino
  tag: 460
  pullPolicy: IfNotPresent

server:
  workers: 3
  node:
    environment: production
    dataDir: /data/trino
    pluginDir: /usr/lib/trino/plugin
  log:
    trino:
      level: INFO
  config:
    path: /etc/trino
    https:
      enabled: false
      port: 8443
      keystore:
        path: ""
    authenticationType: ""
    query:
      maxMemory: "4GB"
  exchangeManager: {}

  workerExtraConfig: ""
  coordinatorExtraConfig: ""
  autoscaling:
    enabled: true
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 80
    behavior: {}

catalogs:
  iceberg: |-
    connector.name=iceberg
    iceberg.catalog.type=nessie
    iceberg.file-format=PARQUET
    iceberg.nessie-catalog.uri=http://nessie.nessie.svc.cluster.local:19120/api/v2
    iceberg.nessie-catalog.default-warehouse-dir=s3a://metastore/warehouse/
    fs.native-s3.enabled=true
    s3.endpoint=http://minio.minio.svc.cluster.local
    s3.region=us-east-1
    s3.path-style-access=true
    s3.aws-access-key=${AWS_ACCESS_KEY_ID}
    s3.aws-secret-key=${AWS_SECRET_ACCESS_KEY}

envFrom:
  - secretRef:
      name: minio-credentials

securityContext:
  runAsUser: 1000
  runAsGroup: 1000

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

shareProcessNamespace:
  coordinator: false
  worker: false

service:
  annotations: {}
  type: ClusterIP
  port: 8080
  nodePort: ""

coordinator:
  jvm:
    maxHeapSize: "8G"
    gcMethod:
      type: "UseG1GC"
      g1:
        heapRegionSize: "32M"

  config:
    memory:
      heapHeadroomPerNode: ""
    query:
      maxMemoryPerNode: "1GB"

  terminationGracePeriodSeconds: 30
  # resources:
  #   requests:
  #     memory: 400Mi
  #     cpu: 15m
  #   limits:
  #     memory: 1Gi
  #     cpu: 350m

worker:
  jvm:
    maxHeapSize: "8G"
    gcMethod:
      type: "UseG1GC"
      g1:
        heapRegionSize: "32M"

  config:
    memory:
      heapHeadroomPerNode: ""
    query:
      maxMemoryPerNode: "1GB"

  gracefulShutdown:
    enabled: false
    gracePeriodSeconds: 120

  terminationGracePeriodSeconds: 30
  # resources:
  #   requests:
  #     memory: 400Mi
  #     cpu: 15m
  #   limits:
  #     memory: 1Gi
  #     cpu: 350m

kafka:
  mountPath: "/etc/trino/schemas"
