global:
  jobs:
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 2Gi
        cpu: 3000m

webapp:
  replicaCount: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 500m

pod-sweeper:
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 200m

server:
  replicaCount: 1
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 4Gi
      cpu: 2000m

worker:
  replicaCount: 1
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 4Gi
      cpu: 2000m

airbyte-bootloader:
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 500m

temporal:
  replicaCount: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 2Gi
      cpu: 1000m

postgresql:
  enabled: true

minio:
  storage:
    volumeClaimValue: 1Gi

cron:
  replicaCount: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 250m

connector-builder-server:
  replicaCount: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 500m

airbyte-api-server:
  replicaCount: 1
  resources:
    requests:
      memory: 500Mi
      cpu: 250m
    limits:
      memory: 2Gi
      cpu: 1000m
