version: 2

sources:
- name: minio
  database: minio
  schema: landing
  tables:
  - name: binancecoin
  - name: bitcoin
  - name: cardano
  - name: ethereum
  - name: solana
- name: iceberg_bronze
  database: iceberg
  schema: bronze
  tables:
  - name: binancecoin_bronze
  - name: bitcoin_bronze
  - name: cardano_bronze
  - name: ethereum_bronze
  - name: solana_bronze
