apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-prometheus
  namespace: gitops
spec:
  project: default
  destination:
    name: 'victor-lab'
    namespace: observability-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - repoURL: 'https://github.com/victoru2/trino-lakehouse-lab.git'
    targetRevision: main
    ref: trino-lakehouse-lab
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.27.0
    helm:
      valueFiles:
      - $trino-lakehouse-lab/observability/infra/prometheus/helm/values.yaml
