apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-metastore
  namespace: gitops
spec:
  project: default
  destination:
    name: 'victor-lab'
    namespace: metastore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - repoURL: 'https://github.com/victoru2/trino-lakehouse-lab.git'
    targetRevision: main
    ref: trino-lakehouse-lab
  - repoURL: https://gradiant.github.io/bigdata-charts
    chart: hive-metastore
    targetRevision: 0.1.3
    helm:
      valueFiles:
      - $trino-lakehouse-lab/hive-metastore/helm/values.yaml
