apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: gitops
spec:
  project: default
  destination:
    name: 'victor-lab'
    namespace: dataviz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - repoURL: 'https://github.com/victoru2/trino-lakehouse-lab.git'
    targetRevision: main
    ref: trino-lakehouse-lab
  - repoURL: http://apache.github.io/superset
    chart: superset
    targetRevision: 0.12.11
    helm:
      valueFiles:
      - $trino-lakehouse-lab/superset/helm/values.yaml
